### ISSUE TITLE
Ordering issue

### ISSUE THREAD

**Issue by hisusqristos** [hisusqristos/karpet#2]
`TL;DR:` Im changing outfile to outDir to use comfortable modules 

setting [outFile](https://www.typescriptlang.org/tsconfig#outFile) in tsconfig.json was an experimental thing to do. outFile works with limited modules (`None`, `System`, `Amd`). Here we use `None` which means there is no import/export/require methods to grab variables from vneshni mir. you can reference those variables and vsyo, no red underlines. __But__ the ordering is messed up. you define variable `x` in file `AAA.ts` then try to use it in `index.ts` and get </br>

`Block-scoped variable 'x' used before its declaration.`

haskacaq? petqa mi hat el dnes hertakanutyuny mtaces<kak nexuy delat :/>.

**Comment by hisusqristos** [comment]
tho i struggle with choosing modules. is commonJS ok?

**Comment by antaranyan** [comment]
CommonJS might be ok, but struggle is not.

**Comment by antaranyan** [comment]
There was a long evolution of how we put JS in web page to work. 

Evan You, creator of Vue.js and many other things, gave a nice presentation of the history, arriving why they built [Vite](https://vitejs.dev/) for front-end tooling.
