### ISSUE TITLE
rules

### ISSUE THREAD

**Issue by hisusqristos** [hisusqristos/karpet#4]
we have

- top-left-corner
- top-right-corner
- bottom-right-corner
- bottom-left-corner
- top-edge
- bottom-edge
- left-edge
- right-edge
- internal

and the rules (work in process)
| part| up | right | bottom | left |
|---|---|---|---|---|
| top-left-corner || topEdge, topRightCorner | leftEdge, bottomLeftCorner ||
| top-rightt-corner ||| rightEdge, bottomRightCorner | topEdge, topLeftCorner |
| bottom-right-corner | rightEdge, topRightCorner ||| bottomEdge, bottomLeftCorner |
| bottom-left-corner | leftEdge, topLeftCorner | bottomEdge, bottomRightEdge |||
| top-edge || topEdge, topRighttCorner | bottomEdge, internal | topLeftCorner, topEdge |
| bottom-edge | internal, topEdge | bottomRightCorner, bottomEdge || bottomEdge, bottomLeftCorner |
| left-edge | leftEdge, topLeftEdge | rightEdge, internal | leftEdge, bottomLeftEdge |  |
| right-edge | rightEdge, topRightCorner |  | rightEdge, bottomRightCorner | leftEdge, internal |
| internal | topEdge, internal | rightEdge, internal | bottomEdge, internal | leftEdge |

_Originally posted by @hisusqristos in https://github.com/hisusqristos/karpet/issues/3#issuecomment-1607669145_

**Comment by antaranyan** [comment]
> we have
> 
>   * top-left-corner
>   * top-right-corner
>   * bottom-right-corner
>   * ...

hm? what a rectangular arrow you imagine here?

**Comment by hisusqristos** [comment]
es karpeti ktoriknern en

**Comment by hisusqristos** [comment]
mm done
